### PR TITLE
Init commit to Contrubutions.md

### PR DESCRIPTION
**Pull request by bilal-aamer**
This PR is in response to the Issue #6 

Here we state the general contrubuting values, guidelines, etc. that a contrubuter must abide by when contrubuting towards `Awsome-Lightning` !

This is an initial commit! More are appreciated. :)

### CODE REVIEW

**Comment by bilal-aamer** [comment]
@aniketmaurya Please look into this PR!

**Comment by aniketmaurya** [comment]
Thanks for the PR @bilal-aamer! Could you create `CONTRIBUTIONS.md` inside `.github` instead of the contributors file please.

**Comment by bilal-aamer** [comment]
Sure @aniketmaurya, will do!

**Comment by bilal-aamer** [comment]
Sure,

GOTO PR #9

**Comment by aniketmaurya** [comment]
hey @bilal-aamer, you can update the same PR. [Here](https://www.youtube.com/watch?list=PLaMu-SDt_RB51u2kyttt3tDvXCp-KMw4A&v=HF6KAFDk9dY&feature=youtu.be) is a Lightning Bits tutorial for this.

**Pull request closed without merging**
